---
- name: "check chrome already is present"
  stat:
    path: "/usr/bin/google-chrome-stable"
  register: installDirChrome

- block:
  - name: "download chrome"
    get_url:
      url: "{{ chrome_download_url }}"
      dest: "/tmp/{{ chrome_temp_file }}"

  - name: "install chrome"
    become: yes
    apt:
      deb: "/tmp/{{ chrome_temp_file }}"

  - name: "copy pinnedChrome.sh"
    copy:
      src: "pinnedChrome.sh"
      dest: "/home/vagrant/pinnedChrome.sh"
      owner: "vagrant"
      group: "vagrant"
      mode: "777"

  - name: "execute pinnedChrome.sh"
    command: "/home/vagrant/pinnedChrome.sh"

  - name: "delete pinnedChrome.sh"
    file:
      path: "/home/vagrant/pinnedChrome.sh"
      state: absent
  when: not installDirChrome.stat.exists