---
- name: Check current docker-compose version.
  command: "localectl status"
  register: localectl_status

- block:
    - name: Change keyboard layout to german
      command: "sudo localectl set-x11-keymap de pc105 nodeadkeys compose:rwin"

    - name: propagete changes to system
      command: "sudo update-locale"
  when: not localectl_status.stdout_lines is search("de-latin1-nodeadkeys")