---
- name: "enable auto login"
  become: yes
  replace:
    path: "/etc/gdm3/custom.conf"
    regexp: "#  AutomaticLoginEnable = true"
    replace: "AutomaticLoginEnable = true"

- name: "set vagrant to login automatically"
  become: yes
  replace:
    path: "/etc/gdm3/custom.conf"
    regexp: "#  AutomaticLogin = user1"
    replace: "AutomaticLogin = vagrant"