---
- hosts: localhost
  connection: local
  strategy: debug

  roles:
    - role: cleanup-apps
    - role: locale-de
    - role: keyboard-layout-de
    - role: timezone-berlin
    - role: disable-lock-screen
    - role: autologin
    - role: chrome
    - role: resize-desktop
    - role: apt-install-items
      packages:
        - git
        - unzip
        - curl
        - default-jdk
    - role: intellij-community
