---
- hosts: localhost
  connection: local
  strategy: debug

  roles:
#    - role: snap-install-items
#      packages:
#        - software-properties-common
#        - vim
#        - curl
#        - unzip
#        - git
    - role: autologin
    - role: resize-desktop
      resolution: 1920x1080
    - role: chrome
