---
- hosts: localhost
  connection: local
  strategy: debug

  roles:
    - role: apt-uninstall-items
      packages:
        - libreoffice*
        - shotwell*
        - firefox
        - thunderbird
    - role: locale-de
    - role: keyboard-layout-de
    - role: timezone-berlin
    - role: resize-desktop
      resolution: 1920x1080
    - role: autologin
#    - role: snap-install-items
#      packages:
#        - software-properties-common
#        - vim
#        - curl
#        - unzip
#        - git
    - role: chrome
