---
- hosts: localhost
  connection: local
  strategy: debug

  roles:
    - role: cleanup-apps
    - role: locale-de
    - role: keyboard-layout-de
    - role: timezone-berlin
    - role: disable-lock-screen
    - role: autologin
    - role: chrome # TODO es fehlt noch das Icon in der Taskleiste
    - role: resize-desktop
      resolution: 1920x1080
#    - role: snap-install-items
#      packages:
#        - software-properties-common
#        - vim
#        - curl
#        - unzip
#        - git
