---
- hosts: localhost
  connection: local
  strategy: debug

  roles:
#     - role: apt-install-items
#       packages:
#         - software-properties-common
#         - vim
#         - curl
#         - unzip
#         - git
#         - terminator
    - role: autologin
    - role: resize-desktop
      resolution: 1920x1080