---
- name: "replace width of screen resolution"
  replace:
    path: "~/.config/monitors.xml"
    regexp: "<width>\\d*<\/width>"
    replace: "<width>{{ resize_desktop_width }}<\/width>"

- name: "replace height of screen resolution"
  replace:
    path: "~/.config/monitors.xml"
    regexp: "<height>\\d*<\/height>"
    replace: "<height>{{ resize_desktop_height }}<\/height>"

- name: "replace rate of screen resolution"
  replace:
    path: "~/.config/monitors.xml"
    regexp: "<rate>\\d*<\/rate>"
    replace: "<rate>{{ resize_desktop_rate }}<\/rate>"

- name: "copy monitors.xml"
  become: yes
  copy:
    src: "~/.config/monitors.xml"
    dest: "/var/lib/gdm3/.config/monitors.xml"