---
- name: "find files in hidden directory .config"
  become: yes
  find:
    hidden: yes
    recurse: true
    paths: "/home/vagrant/"
    patterns:
      - xdg-terminals.list
  register: find_hidden

- name: "show find_hidden"
  debug:
    msg: "could not change screen resolution, try it again with `--provision`"
  when: find_hidden.matched == 0

- name: "copy monitors template"
  become: yes
  template:
    src: "monitors.j2"
    dest: "/home/vagrant/.config/monitors.xml"
    owner: "vagrant"
    group: "vagrant"
    mode: "0664"
  when: find_hidden.matched >= 1

- name: "copy monitors.xml"
  become: yes
  copy:
    src: "/home/vagrant/.config/monitors.xml"
    dest: "/var/lib/gdm3/.config/monitors.xml"
    owner: "gdm"
    group: "gdm"
    mode: "0664"
  when: find_hidden.matched >= 1