---
- name: "uninstall packages with apt"
  become: yes
  apt:
    name: "{{ item }}"
    state: absent
    autoremove: yes
    purge: yes
    update_cache: yes
  loop: "{{ cleanup_apps_apt }}"

- name: "uninstall packages with snap"
  become: yes
  snap:
    name: "{{ item }}"
    state: "absent"
  loop: "{{ cleanup_apps_snap }}"